# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-25 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='assets/picture/eduplace')),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.PlaceCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tags', models.ManyToManyField(blank=True, related_name='faculty_tags', to='place.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tags', models.ManyToManyField(blank=True, related_name='studyprogram_tags', to='place.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('picture', models.ImageField(upload_to='assets/picture/university')),
                ('is_active', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='university_tags', to='place.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='educationplace',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Faculty'),
        ),
        migrations.AddField(
            model_name='educationplace',
            name='studyprogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.StudyProgram'),
        ),
        migrations.AddField(
            model_name='educationplace',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='education_place_tags', to='place.Tag'),
        ),
        migrations.AddField(
            model_name='educationplace',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.University'),
        ),
    ]
